"""Addedd folder and layer models

Revision ID: 97bc66188d3e
Revises: 
Create Date: 2024-12-17 16:57:03.544412

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '97bc66188d3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modified_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('modification_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folder_name'), 'folder', ['name'], unique=True)
    op.create_table('layer',
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modified_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_layer_folder_id'), 'layer', ['folder_id'], unique=False)
    op.create_index(op.f('ix_layer_name'), 'layer', ['name'], unique=True)
    op.create_index(op.f('ix_layer_parent_id'), 'layer', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_layer_parent_id'), table_name='layer')
    op.drop_index(op.f('ix_layer_name'), table_name='layer')
    op.drop_index(op.f('ix_layer_folder_id'), table_name='layer')
    op.drop_table('layer')
    op.drop_index(op.f('ix_folder_name'), table_name='folder')
    op.drop_table('folder')
    # ### end Alembic commands ###
