"""Removed parent_id from layer

Revision ID: 0d5ed04fb596
Revises: 97bc66188d3e
Create Date: 2024-12-30 13:32:51.973937

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0d5ed04fb596'
down_revision = '97bc66188d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_layer_parent_id', table_name='layer')
    op.drop_column('layer', 'parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_layer_parent_id', 'layer', ['parent_id'], unique=False)
    # ### end Alembic commands ###
