import os

SECURITY_TYPE = os.environ.get(
    "SECURITY_TYPE", "KEYCLOAK-INFO"
).upper()

KEYCLOAK_PROTOCOL = os.environ.get(
    "KEYCLOAK_PROTOCOL", "http"
)
KEYCLOAK_HOST = os.environ.get(
    "KEYCLOAK_HOST", "keycloak"
)
KEYCLOAK_PORT = os.environ.get(
    "KEYCLOAK_PORT", "8080"
)
KEYCLOAK_REDIRECT_PROTOCOL = os.environ.get(
    "KEYCLOAK_REDIRECT_PROTOCOL", ""
)
KEYCLOAK_REDIRECT_HOST = os.environ.get(
    "KEYCLOAK_REDIRECT_HOST", ""
)
KEYCLOAK_REDIRECT_PORT = os.environ.get(
    "KEYCLOAK_REDIRECT_PORT", ""
)
KEYCLOAK_REALM = os.environ.get(
    "KEYCLOAK_REALM", "avataa"
)

if KEYCLOAK_REDIRECT_PROTOCOL is None:
    KEYCLOAK_REDIRECT_PROTOCOL = KEYCLOAK_PROTOCOL
if KEYCLOAK_REDIRECT_HOST is None:
    KEYCLOAK_REDIRECT_HOST = KEYCLOAK_HOST
if KEYCLOAK_REDIRECT_PORT is None:
    KEYCLOAK_REDIRECT_PORT = KEYCLOAK_PORT

KEYCLOAK_URL = f"{KEYCLOAK_PROTOCOL}://{KEYCLOAK_HOST}:{KEYCLOAK_PORT}"
KEYCLOAK_PUBLIC_KEY_URL = (
    f"{KEYCLOAK_URL}/realms/{KEYCLOAK_REALM}"
)
KEYCLOAK_REDIRECT_URL = f"{KEYCLOAK_REDIRECT_PROTOCOL}://{KEYCLOAK_REDIRECT_HOST}:{KEYCLOAK_REDIRECT_PORT}"
KEYCLOAK_TOKEN_URL = f"{KEYCLOAK_REDIRECT_URL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/token"
KEYCLOAK_AUTHORIZATION_URL = f"{KEYCLOAK_REDIRECT_URL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/auth"

if KEYCLOAK_REDIRECT_PROTOCOL is None:
    KEYCLOAK_REDIRECT_PROTOCOL = KEYCLOAK_PROTOCOL

if KEYCLOAK_REDIRECT_HOST is None:
    KEYCLOAK_REDIRECT_HOST = KEYCLOAK_HOST

if KEYCLOAK_REDIRECT_PORT is None:
    KEYCLOAK_REDIRECT_PORT = KEYCLOAK_PORT

KEYCLOAK_PUBLIC_KEY_URL = (
    f"{KEYCLOAK_URL}/realms/{KEYCLOAK_REALM}"
)
KEYCLOAK_REDIRECT_URL = f"{KEYCLOAK_REDIRECT_PROTOCOL}://{KEYCLOAK_REDIRECT_HOST}"
if KEYCLOAK_REDIRECT_PORT:
    KEYCLOAK_REDIRECT_URL += (
        f":{KEYCLOAK_REDIRECT_PORT}"
    )

KEYCLOAK_AUTHORIZATION_URL = f"{KEYCLOAK_REDIRECT_URL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/auth"
